Repository SolarArbiter/solarforecastarbiter-dashboard, pull requests merged in 2020-07, with the labels that each got.

#302 replace special characters that are in prob. fx metrics
  sfa_dash/static/js/report-rendering.js
Labels: bug

#297 Add costs to reports
  sfa_dash/conftest.py
  sfa_dash/form_utils/converters.py
  sfa_dash/form_utils/tests/test_converter.py
  sfa_dash/static/css/styles.css
  sfa_dash/static/js/report-form-handling.js
  sfa_dash/static/js/report-form-utilities.js
  sfa_dash/templates/forms/base/base_report_form.html
  sfa_dash/templates/head.html
Labels: enhancement

#311 Forecast fill
  sfa_dash/filters.py
  sfa_dash/form_utils/converters.py
  sfa_dash/form_utils/tests/test_converter.py
  sfa_dash/static/js/event-report-form-handling.js
  sfa_dash/static/js/probabilistic-report-form-handling.js
  sfa_dash/static/js/report-form-handling.js
  sfa_dash/static/js/report-form-utilities.js
  sfa_dash/templates/forms/base/base_report_form.html
Labels: enhancement

#310 Reference forecast selection issue
  sfa_dash/static/css/styles.css
  sfa_dash/static/js/probabilistic-report-form-handling.js
  sfa_dash/static/js/report-form-handling.js
Labels: bug

#313 Report clone button
  sfa_dash/filters.py
  sfa_dash/form_utils/converters.py
  sfa_dash/form_utils/tests/test_converter.py
  sfa_dash/templates/data/intermediate_report.html
Labels: bug, enhancement

#282 Breadcrumb tuples
  sfa_dash/blueprints/aggregates.py
  sfa_dash/blueprints/base.py
  sfa_dash/blueprints/data_listing.py
  sfa_dash/blueprints/main.py
  sfa_dash/blueprints/tests/test_base.py
  sfa_dash/tests/views/test_success.py
Labels: bug

#315 fire forecast filtering when units are set
  sfa_dash/static/js/probabilistic-report-form-handling.js
  sfa_dash/static/js/report-form-handling.js
  sfa_dash/static/js/report-form-utilities.js
Labels: bug

#317 trigger filter forecast through site change callback to avoid scoping…
  sfa_dash/static/js/probabilistic-report-form-handling.js
  sfa_dash/static/js/report-form-handling.js
Labels: bug

#319 Fix climate zone filtering
  sfa_dash/filters.py
  sfa_dash/static/js/table-search.js
  sfa_dash/templates/data/metadata/site_metadata.html
  sfa_dash/templates/data/table/site_table.html
Labels: bug

#320 Retain variable selection through object pair selection
  sfa_dash/static/js/report-form-utilities.js
Labels: bug

#327 Fix permissions with object type 'report'
  sfa_dash/blueprints/admin.py
  sfa_dash/templates/forms/admin/permission_macros.jinja
  sfa_dash/templates/forms/admin/permission_object_addition.html
  sfa_dash/templates/forms/admin/role_macros.jinja
  sfa_dash/templates/forms/admin/role_permission_addition.html
  sfa_dash/templates/forms/admin/user_macros.jinja
  sfa_dash/templates/forms/form_macros.jinja
Labels: bug

#332 add retry adapter for API requests
  sfa_dash/api_interface/tests/app.py
  sfa_dash/api_interface/tests/test_init.py
  sfa_dash/blueprints/auth0.py
Labels: enhancement

#330 Mesage flashing safety
  sfa_dash/api_interface/util.py
  sfa_dash/templates/sections/notifications.html
  sfa_dash/tests/views/test_api_404.py
Labels: bug

#334 retry get on chunked encoding error
  sfa_dash/api_interface/__init__.py
  sfa_dash/api_interface/tests/app.py
  sfa_dash/api_interface/tests/test_init.py
Labels: bug

#339 Catch role sharing error
  sfa_dash/blueprints/admin.py
  sfa_dash/templates/forms/admin/base/base_admin_form.html
  sfa_dash/templates/forms/admin/permission_macros.jinja
  sfa_dash/templates/forms/admin/role_form.html
  sfa_dash/templates/forms/admin/role_grant.html
Labels: bug

#340 Hide on create perm
  sfa_dash/blueprints/admin.py
  sfa_dash/static/js/form-validation.js
  sfa_dash/templates/forms/admin/permission.html
  sfa_dash/templates/forms/admin/permissions_form.html
Labels: bug

#341 Limit variable options when site does not have modeling params
  sfa_dash/filters.py
  sfa_dash/templates/forms/cdf_forecast_group_form.html
  sfa_dash/templates/forms/forecast_form.html
  sfa_dash/templates/forms/observation_form.html
  sfa_dash/templates/forms/site_form.html
Labels: UI

#346 Conditional action display
  sfa_dash/__init__.py
  sfa_dash/api_interface/users.py
  sfa_dash/blueprints/admin.py
  sfa_dash/blueprints/reports.py
  sfa_dash/template_globals.py
  sfa_dash/templates/data/aggregate.html
  sfa_dash/templates/data/aggregates.html
  sfa_dash/templates/data/intermediate_report.html
  sfa_dash/templates/data/reports.html
  sfa_dash/templates/data/site.html
  sfa_dash/templates/data/table/cdf_forecast_table.html
  sfa_dash/templates/data/table/forecast_table.html
  sfa_dash/templates/data/table/observation_table.html
  sfa_dash/templates/data/table/site_table.html
  sfa_dash/templates/forms/admin/permissions.html
  sfa_dash/templates/forms/admin/roles.html
Labels: UI, enhancement
